#!/usr/bin/env node

const program = require('commander');

program
  .description('Compares two configuration files and shows a difference.')
  .usage('[options] <firstConfig> <secondConfig>')
  .version('0.1.0')

program.on('--help', function(){
  console.log('  -f, --format [type]', 'output format');
});

program.parse(process.argv);

